INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=51.507351&lon=-0.127696&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:42:16] "GET /weather/london HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:42:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:43:04] "[32mGET /map/london HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:43:04] "GET /map/-0.127696/51.507351?WEATHER_API=1123bb2d4b885327b25dcfe7dee216a7 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:43:04] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:43:13] "[31m[1mPOST /map/-0.127696/51.507351?WEATHER_API=1123bb2d4b885327b25dcfe7dee216a7 HTTP/1.1[0m" 405 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:44:42] "[31m[1mPOST /map/-0.127696/51.507351?WEATHER_API=1123bb2d4b885327b25dcfe7dee216a7 HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:45:22] "GET /map/-0.127696/51.507351 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:45:24] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:50:16] "[32mGET /map/london HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:50:17] "GET /map/-0.127696/51.507351 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:50:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:50:28] "[32mPOST /map/-0.127696/51.507351 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:50:29] "[32mGET /map/Краков HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:50:29] "GET /map/19.936742/50.061971 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:50:29] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:55:57] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:55:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 19:56:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 20:02:16] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 20:02:16] "GET /static/css/style.css HTTP/1.1" 200 -
ERROR:main:Exception on /weather/london [GET]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CECD9E91C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geocode-maps.yandex.ru', port=443): Max retries exceeded with url: /1.x/?apikey=40d1649f-0493-4b70-98ba-98533de7710b&geocode=london&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CECD9E91C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\data\weather.py", line 26, in get_weather
    response = requests.get(geocoder_req).json()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geocode-maps.yandex.ru', port=443): Max retries exceeded with url: /1.x/?apikey=40d1649f-0493-4b70-98ba-98533de7710b&geocode=london&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CECD9E91C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 20:02:31] "[35m[1mGET /weather/london HTTP/1.1[0m" 500 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=51.507351&lon=-0.127696&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 20:02:58] "GET /weather/london HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 20:02:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 20:03:25] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Apr/2022 20:03:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
ERROR:main:Exception on /weather/london [GET]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CECDA77610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geocode-maps.yandex.ru', port=443): Max retries exceeded with url: /1.x/?apikey=40d1649f-0493-4b70-98ba-98533de7710b&geocode=london&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CECDA77610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\data\weather.py", line 26, in get_weather
    response = requests.get(geocoder_req).json()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geocode-maps.yandex.ru', port=443): Max retries exceeded with url: /1.x/?apikey=40d1649f-0493-4b70-98ba-98533de7710b&geocode=london&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CECDA77610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 18:06:23] "[35m[1mGET /weather/london HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
ERROR:main:Exception on /user/artlvr [GET]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: users.avatar_image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 273, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\local.py", line 436, in __get__
    obj = instance._get_current_object()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\local.py", line 565, in _get_current_object
    return self.__local()  # type: ignore
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 359, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\login_manager.py", line 355, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 40, in load_user
    return db_sess.query(User).get(user_id)
  File "<string>", line 2, in get
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\deprecations.py", line 401, in warned
    return fn(*args, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 943, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 947, in _get_impl
    return self.session._get_impl(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 2892, in _get_impl
    return db_load_fn(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1620, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1487, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1851, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2032, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: users.avatar_image
[SQL: SELECT users.id AS users_id, users.name AS users_name, users.about AS users_about, users.city AS users_city, users.email AS users_email, users.hashed_password AS users_hashed_password, users.created_date AS users_created_date, users.avatar_image AS users_avatar_image 
FROM users 
WHERE users.id = ?]
[parameters: ('1',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:02:45] "[35m[1mGET /user/artlvr HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:03:40] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:03:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:03:46] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:03:46] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
ERROR:main:Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 6 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 70, in register
    db_sess.commit()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3363, in flush
    self._flush(objects)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3463, in _flush
    flush_context.execute()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1237, in _emit_insert_statements
    result = connection._execute_20(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1620, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1487, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1851, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2032, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 6 - probably unsupported type.
[SQL: INSERT INTO users (name, about, city, email, hashed_password, created_date, avatar_image) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('artlvr', '**information about user**', 'Washington', 'marincyrill@yandex.ru', 'pbkdf2:sha256:260000$MSyAOTl9808OqZCi$693734411ff8190ee3896de4b340117f831c8824cacf94ea109315289261cae5', '2022-04-18 20:04:38.921944', <sqlalchemy.sql.elements.Null object at 0x000001E7646BE970>)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:04:39] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
ERROR:main:Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 6 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 72, in register
    db_sess.commit()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3363, in flush
    self._flush(objects)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3463, in _flush
    flush_context.execute()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1237, in _emit_insert_statements
    result = connection._execute_20(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1620, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1487, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1851, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 2032, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 6 - probably unsupported type.
[SQL: INSERT INTO users (name, about, city, email, hashed_password, created_date, avatar_image) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('artlvr', '**information about user**', 'Washington', 'marincyrill@yandex.ru', 'pbkdf2:sha256:260000$HgzeGluWbY39Dli8$2639397d893e74fd8c73ad3b79a8871382d01f67afb0396bc978af91034bf8bc', '2022-04-18 20:07:08.418631', <function null at 0x0000020F6D081820>)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:07:08] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:28] "[32mPOST /register HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:28] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:29] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:35] "[32mPOST /login HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:37] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:38] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:47] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:47] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
ERROR:main:Exception on /user/None [GET]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 98, in user
    if user.name == flask_login.current_user.name:
AttributeError: 'NoneType' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 279, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 98, in user
    if user.name == flask_login.current_user.name:
AttributeError: 'NoneType' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:08:47] "[35m[1mGET /user/None HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
ERROR:main:Exception on /user/artlvr [GET]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 107, in user
    return render_template('user.html', **params)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Павел\PycharmProjects\weather_web_project\templates\base.html", line 44, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Павел\PycharmProjects\weather_web_project\templates\user.html", line 8, in block 'content'
    <img src="{{ user.avatar(128)}}", alt="oops, something went wrong">
  File "C:\Users\Павел\PycharmProjects\weather_web_project\data\users.py", line 31, in avatar
    if self.avatar_image == sqlalchemy.null():
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 3890, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:09:25] "[35m[1mGET /user/artlvr HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:11:10] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:11:12] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:11:39] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:11:39] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:13:08] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 100, in user
    filename = images.save(form.image.data)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_uploads.py", line 416, in save
    raise UploadNotAllowed()
flask_uploads.UploadNotAllowed
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:13:48] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 100, in user
    filename = images.save(form.image.data)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_uploads.py", line 416, in save
    raise UploadNotAllowed()
flask_uploads.UploadNotAllowed
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:23:18] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:23:33] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:23:35] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:23:55] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:23:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:24:06] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:24:54] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:24:54] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:42:23] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:42:24] "[33mGET /uploads/purple_guy_2.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:42:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:46:01] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:46:02] "[33mGET /uploads/purple_guy.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:46:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:46:14] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:46:14] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:46:14] "[33mGET /uploads/purple_guy_1.jpg HTTP/1.1[0m" 404 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:50:14] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:50:14] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:50:14] "[33mGET /uploads/hungary.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:50:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:51:26] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:51:26] "[33mGET /uploads/hungary_1.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:51:28] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:54:30] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:54:31] "[33mGET /uploads/hungary_2.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:54:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:56:03] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:56:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:56:03] "[33mGET /uploads/hungary_3.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\main.py", line 105, in user
    return render_template('user.html', **params)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Павел\PycharmProjects\weather_web_project\templates\base.html", line 44, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Павел\PycharmProjects\weather_web_project\templates\user.html", line 8, in block 'content'
    <img src="{{ user.avatar(128)}}", alt="oops, something went wrong">
  File "C:\Users\Павел\PycharmProjects\weather_web_project\data\users.py", line 36, in avatar
    return url_for('uploads', filename=self.avatar_image)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\werkzeug\routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'uploads' with values ['filename']. Did you mean '_uploads.uploaded_file' instead?
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 20:58:12] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1599, in ensure_sync
    return self.async_to_sync(func)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1620, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:08] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1599, in ensure_sync
    return self.async_to_sync(func)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1620, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:08] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1599, in ensure_sync
    return self.async_to_sync(func)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1620, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:08] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1599, in ensure_sync
    return self.async_to_sync(func)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1620, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:16] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1599, in ensure_sync
    return self.async_to_sync(func)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1620, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:16] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
ERROR:main:Exception on /user/artlvr [POST]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1599, in ensure_sync
    return self.async_to_sync(func)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1620, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:16] "[35m[1mPOST /user/artlvr HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:39] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:40] "[33mGET /uploads/hungary_5.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:00:41] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:01:46] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:01:46] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:02:04] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:02:36] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:02:36] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:02:59] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:02:59] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:02:59] "[33mGET /uploads/knight.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:03:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:05:21] "[33mGET /user/uploads/knight.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:05:34] "[33mGET /uploads/knight.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:05:39] "[33mGET /user/uploads/knight.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:05:45] "[33mGET /user/uploads/knight.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:05:59] "[33mGET /uploads/knight.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:08:54] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:08:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:08:56] "GET /static/uploads/knight.jpg HTTP/1.1" 200 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:19:27] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:19:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:20:39] "[32mGET /map/Washington HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:20:40] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Apr/2022 21:20:40] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.8:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.8:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:24] "[32mGET /user/artlvr HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:24] "GET /login?next=%2Fuser%2Fartlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:24] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:25] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:32] "[32mPOST /login?next=%2Fuser%2Fartlvr HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:35] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:35] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:36] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:36] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:42] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:42] "[33mGET /static/tmp/pix.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:58:46] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:59:18] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:59:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 16:59:18] "[33mGET /static/tmp/pix_1.png HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:01:15] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:01:15] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:01:15] "GET /static/tmp/pix.png HTTP/1.1" 200 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:01:25] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:01:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:01:25] "GET /static/tmp/pix.jpeg HTTP/1.1" 200 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:02:06] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:02:06] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:02:06] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:06:44] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:14:15] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:14:15] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:14:15] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:15:19] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:15:19] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:15:19] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:21:23] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:21:23] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:21:23] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:25:33] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:25:34] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:25:34] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:26:16] "GET /static/tmp/pix.jpeg HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:29:52] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:29:52] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:29:52] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:32:03] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:32:03] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:32:03] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:33:51] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:33:51] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:33:51] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:03] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:03] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:09] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:09] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:09] "[36mGET /static/tmp/pix.jpeg HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:22] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:22] "GET /static/tmp/maxresdefault.jpg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:34:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:42:53] "[32mGET /map/Washington HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:42:53] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:42:53] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:43:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:45:56] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:45:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:45:56] "[36mGET /static/tmp/maxresdefault.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:46:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
ERROR:main:Exception on /weather/Washington [GET]
Traceback (most recent call last):
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\marin\Desktop\weather\data\weather.py", line 53, in get_weather
    "city": weather_response["name"] if weather_response["name"] else city,
KeyError: 'name'
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:51:58] "[35m[1mGET /weather/Washington HTTP/1.1[0m" 500 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
ERROR:main:Exception on /weather/Washington [GET]
Traceback (most recent call last):
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\marin\Desktop\weather\data\weather.py", line 53, in get_weather
    "city": weather_response["name"] if weather_response["name"] else city,
KeyError: 'name'
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:53:14] "[35m[1mGET /weather/Washington HTTP/1.1[0m" 500 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:53:24] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:53:24] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:53:24] "[36mGET /static/tmp/maxresdefault.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:55:19] "[32mGET /map/Washington HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:55:19] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:55:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 17:58:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:01:44] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:01:44] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:02:02] "[32mPOST /map/-77.036536/38.899513 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:02:02] "[32mGET /map/Нижневартовск,%20Ханты-Мансийский%20автономный%20округ%20-%20Югра,%20Россия HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:02:02] "GET /map/76.558902/60.938545 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:02:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:04:25] "[32mPOST /map/76.558902/60.938545 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:04:27] "[32mGET /map/Краков HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:04:27] "GET /map/19.936742/50.061971 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:04:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:04:51] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:14] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:15] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:15] "[36mGET /static/tmp/maxresdefault.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:40] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:40] "[32mGET /weather/Moscow HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:41] "GET /login?next=%2Fweather%2FMoscow HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:41] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:41] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:55] "[32mPOST /register HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:55] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:05:59] "[32mPOST /login HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
ERROR:main:Exception on /weather/Washington [GET]
Traceback (most recent call last):
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\marin\Desktop\weather\data\weather.py", line 53, in get_weather
    "city": weather_response["name"] if weather_response["name"] else city,
KeyError: 'name'
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:00] "[35m[1mGET /weather/Washington HTTP/1.1[0m" 500 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=43.078598&lon=0.19471&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
ERROR:main:Exception on /weather/user [GET]
Traceback (most recent call last):
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\marin\Desktop\weather\data\weather.py", line 53, in get_weather
    "city": weather_response["name"] if weather_response["name"] else city,
KeyError: 'name'
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:08] "[35m[1mGET /weather/user HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:14] "[33mGET /weather/user/great_bot HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:18] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:23] "[32mPOST /login HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
ERROR:main:Exception on /weather/Washington [GET]
Traceback (most recent call last):
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\marin\Desktop\weather\data\weather.py", line 53, in get_weather
    "city": weather_response["name"] if weather_response["name"] else city,
KeyError: 'name'
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:24] "[35m[1mGET /weather/Washington HTTP/1.1[0m" 500 -
ERROR:main:Exception on /user/email@enail.com [GET]
Traceback (most recent call last):
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:/Users/marin/Desktop/weather/main.py", line 90, in user
    if user.name == current_user.name:
AttributeError: 'NoneType' object has no attribute 'name'
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:37] "[35m[1mGET /user/email@enail.com HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:41] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:50] "[33mGET /signup HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:56] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: great_bot
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:57] "GET /user/great_bot HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:06:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: great_bot
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:07:07] "POST /user/great_bot HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:07:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:07:07] "GET /static/tmp/pix_1.png HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:11:46] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:11:46] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:11:53] "[31m[1mPOST / HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:11:58] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:08] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:08] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: great_bot
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:10] "GET /user/great_bot HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:10] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:10] "[36mGET /static/tmp/pix_1.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:12] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:12] "[32mGET /weather/Moscow HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:12] "GET /login?next=%2Fweather%2FMoscow HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:12] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:16] "[32mPOST /login?next=%2Fweather%2FMoscow HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
ERROR:main:Exception on /weather/Washington [GET]
Traceback (most recent call last):
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\marin\AppData\Roaming\Python\Python38\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\marin\Desktop\weather\data\weather.py", line 53, in get_weather
    "city": weather_response["name"] if weather_response["name"] else city,
KeyError: 'name'
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:18] "[35m[1mGET /weather/Washington HTTP/1.1[0m" 500 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:23] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:24] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:12:24] "[36mGET /static/tmp/maxresdefault.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:15:44] "[32mGET /map/Washington HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:15:44] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:15:44] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:26:38] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:26:38] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Apr/2022 18:26:47] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:07] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:08] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:09] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:12] "[32mPOST /login HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:16] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:16] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:24] "[32mGET /map/Washington HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:25] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:24:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:30:02] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:30:58] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:31:00] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:31:24] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:31:56] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Apr/2022 22:31:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:36:57] "[32mGET /user/artlvr HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:36:57] "GET /login?next=%2Fuser%2Fartlvr&username=artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:36:59] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:01] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:06] "[32mPOST /login?next=%2Fuser%2Fartlvr&username=artlvr HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:09] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:09] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:28] "[32mGET /map/Washington HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:28] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:28] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:37:54] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:47:24] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:47:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:49:34] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:49:36] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:52:18] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:52:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:53:19] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:53:21] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:58:53] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 17:58:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:14:28] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:14:29] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:15:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:15:30] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:15:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:16:07] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:16:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:16:30] "[32mPOST /map/-77.036536/38.899513 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:16:30] "[32mGET /map/Нижневартовск HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:16:30] "GET /map/76.558902/60.938545 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:16:30] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:22:11] "GET /map/76.558902/60.938545 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:22:13] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:26:47] "GET /map/76.558902/60.938545 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:26:48] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:36:32] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:36:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:36:32] "[33mGET /static/tmp/maxresdefault.jpg HTTP/1.1[0m" 404 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:36:54] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:36:54] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:36:54] "GET /static/tmp/hero_strikes.gif HTTP/1.1" 200 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:37:10] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:37:10] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:37:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:39:38] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:39:38] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:40:39] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:40:39] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:41:08] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:41:10] "[36mGET /static/tmp/hero_strikes.gif HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:41:10] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:41:19] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:41:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:45:31] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:45:32] "GET /static/css/style.css HTTP/1.1" 200 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:45:40] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:45:40] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:45:52] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:46:44] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:46:46] "[36mGET /static/tmp/hero_strikes.gif HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:46:46] "GET /static/css/style.css HTTP/1.1" 200 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:46:55] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:46:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:47:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:48:08] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:48:10] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:02] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:02] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:02] "[36mGET /static/tmp/hero_strikes.gif HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:21] "POST /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:21] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:21] "GET /static/tmp/knight.jpg HTTP/1.1" 200 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:42] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:49:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:52:59] "GET /static/css/style.css HTTP/1.1" 200 -
ERROR:main:Exception on /weather/Washington [GET]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\data\weather.py", line 27, in get_weather
    pos = response['response']['GeoObjectCollection']['featureMember'][0]['GeoObject']['Point']['pos'].split()
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:53:46] "[35m[1mGET /weather/Washington HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
ERROR:main:Exception on /weather/Washington [GET]
Traceback (most recent call last):
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Павел\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_login\utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Павел\PycharmProjects\weather_web_project\data\weather.py", line 27, in get_weather
    pos = response['response']['GeoObjectCollection']['featureMember'][0]['GeoObject']['Point']['pos'].split()
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:54:55] "[35m[1mGET /weather/Washington HTTP/1.1[0m" 500 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:55:37] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:55:39] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:55:50] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:57:16] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:57:16] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:57:34] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:57:36] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:57:48] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:59:27] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:59:29] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:59:46] "[32mPOST /weather/Washington%20D.C. HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=47.86271&lon=-0.668122&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:59:49] "GET /weather/bordeau HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 18:59:49] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:00] "[32mPOST /weather/Ch\xe2teau-Gontier HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=44.84386&lon=-0.57882&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:02] "GET /weather/bordeaux HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:02] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=41.902695&lon=12.496176&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:29] "GET /weather/rome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:29] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:39] "[32mPOST /weather/Trevi HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=41.904185&lon=12.453255&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:42] "GET /weather/vatikan HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:00:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:01:08] "[32mPOST /weather/State%20of%20the%20Vatican%20City HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=55.749451&lon=37.542824&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:01:12] "GET /weather/москва%20сити HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:01:12] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:02:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=55.749451&lon=37.542824&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:18:26] "GET /weather/москва%20сити HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:18:28] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:18:46] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=55.749451&lon=37.542824&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:33:43] "GET /weather/москва%20сити HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:33:43] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:37:33] "[32mPOST /weather/Dorogomilovo HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=32.816057&lon=35.003125&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:37:35] "GET /weather/Хайфа HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:37:35] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:42:50] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:43:47] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:43:49] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:43:49] "[36mGET /static/tmp/knight.jpg HTTP/1.1[0m" 304 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:43:54] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:43:54] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:49:55] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:49:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:03] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:03] "[32mGET /weather/Moscow HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:03] "GET /login?city=Moscow&next=%2Fweather%2FMoscow HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:05] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:07] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:08] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:08] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:09] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:09] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:54:10] "[33mGET /map/ HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:09] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 19:55:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:03:40] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:03:41] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:03:43] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:03:43] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:03:57] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:04:22] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:04:23] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:26] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:05:27] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:06:22] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:06:23] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:06:52] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:07:22] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:07:23] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:50] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:13:52] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:14:10] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:58] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:15:59] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:17:02] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:17:03] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:18:26] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:18:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:20:02] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:20:03] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:20:56] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:20:57] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:21:48] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:21:49] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:22:24] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:22:26] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:22:57] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:22:58] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:25:07] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:25:09] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:28:44] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:28:46] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:28:49] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:28:49] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:29:48] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:29:49] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:29:55] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:29:55] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:31:22] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:31:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:31:32] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:31:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:20] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:22] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:24] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:24] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:28] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:28] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:35] "[32mPOST /login HTTP/1.1[0m" 302 -
WARNING:root:https://api.openweathermap.org/data/2.5/weather?lat=38.899513&lon=-77.036536&lang=en&appid=1123bb2d4b885327b25dcfe7dee216a7
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:37] "GET /weather/Washington HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:32:38] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
WARNING:root:user: artlvr
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:33:02] "GET /user/artlvr HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:33:02] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:33:02] "[36mGET /static/tmp/knight.jpg HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:33:15] "[32mGET /map/Washington HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:33:15] "GET /map/-77.036536/38.899513 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Apr/2022 20:33:15] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
